// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGBYoIY2dAit3QTHe8FtMHHdXIr_HmRG0',
    appId: '1:610203390909:web:13f13e218b7bb89601f8d4',
    messagingSenderId: '610203390909',
    projectId: 'zuff-b139f',
    authDomain: 'zuff-b139f.firebaseapp.com',
    storageBucket: 'zuff-b139f.firebasestorage.app',
    measurementId: 'G-NBLHXDEQBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtXbxaCy7N36iUYceT3uNhA3IN5SmY8AY',
    appId: '1:610203390909:android:38fc753546908fd101f8d4',
    messagingSenderId: '610203390909',
    projectId: 'zuff-b139f',
    storageBucket: 'zuff-b139f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnh4oXzKRIruGqj0sdohOgCl3lllkpMOE',
    appId: '1:610203390909:ios:f53c083f6ceb51e101f8d4',
    messagingSenderId: '610203390909',
    projectId: 'zuff-b139f',
    storageBucket: 'zuff-b139f.firebasestorage.app',
    iosBundleId: 'com.example.zuff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnh4oXzKRIruGqj0sdohOgCl3lllkpMOE',
    appId: '1:610203390909:ios:f53c083f6ceb51e101f8d4',
    messagingSenderId: '610203390909',
    projectId: 'zuff-b139f',
    storageBucket: 'zuff-b139f.firebasestorage.app',
    iosBundleId: 'com.example.zuff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGBYoIY2dAit3QTHe8FtMHHdXIr_HmRG0',
    appId: '1:610203390909:web:ba5051d28fd2294801f8d4',
    messagingSenderId: '610203390909',
    projectId: 'zuff-b139f',
    authDomain: 'zuff-b139f.firebaseapp.com',
    storageBucket: 'zuff-b139f.firebasestorage.app',
    measurementId: 'G-Y9WF5JQQ1C',
  );
}
