// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKpbNgErWUPVzIkH7HezFaJT7dRLYAHTg',
    appId: '1:329992550325:web:e0aa91cad82614bcebcbfc',
    messagingSenderId: '329992550325',
    projectId: 'zuff-1a15e',
    authDomain: 'zuff-1a15e.firebaseapp.com',
    storageBucket: 'zuff-1a15e.firebasestorage.app',
    measurementId: 'G-7SGB6TLG79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEO0XlDZsXZers0Scrxgg0XKhISlR1RmM',
    appId: '1:329992550325:android:c9789f6eaf98dd59ebcbfc',
    messagingSenderId: '329992550325',
    projectId: 'zuff-1a15e',
    storageBucket: 'zuff-1a15e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsswmK-xMea0L3qWYSVHtAcGmvai5dkes',
    appId: '1:329992550325:ios:de03754a9b7c41cdebcbfc',
    messagingSenderId: '329992550325',
    projectId: 'zuff-1a15e',
    storageBucket: 'zuff-1a15e.firebasestorage.app',
    iosBundleId: 'com.example.zuff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsswmK-xMea0L3qWYSVHtAcGmvai5dkes',
    appId: '1:329992550325:ios:de03754a9b7c41cdebcbfc',
    messagingSenderId: '329992550325',
    projectId: 'zuff-1a15e',
    storageBucket: 'zuff-1a15e.firebasestorage.app',
    iosBundleId: 'com.example.zuff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKpbNgErWUPVzIkH7HezFaJT7dRLYAHTg',
    appId: '1:329992550325:web:5a92697845f480feebcbfc',
    messagingSenderId: '329992550325',
    projectId: 'zuff-1a15e',
    authDomain: 'zuff-1a15e.firebaseapp.com',
    storageBucket: 'zuff-1a15e.firebasestorage.app',
    measurementId: 'G-8NQCHV97VV',
  );

}